### ISSUE TITLE
Use environment variables.

### ISSUE THREAD

**Issue by ejnshtein** [GeneHFang/GraphQLPractice#1]
Here's your [database url](https://github.com/GeneHFang/GraphQLPractice/blob/5ef0d24c4c0b8090b64c5ebfdfc34dd40af3b275/server/app.js#L25).

Use environment variables. Like [here](https://github.com/ejnshtein/nyaasi-bot/blob/aad89dcff18c1c1903bc5b454cbba5a25d164143/core/database/index.js#L10)

**Comment by GeneHFang** [comment]
Thanks for the heads up!

**Comment by ejnshtein** [comment]
Note that your database url is still accessible through commit history, I recommend to change them.
